<h2>FULL THROTTLE</h2>
"GO" begins the race............................
<ul id="submnu">
	<li onclick="introv()">		INTRODUCTION 		</li>
    <li onclick="prblmv()">		PROBLEM STATEMENTS	</li>
    <li onclick="rulesv()">		RULES & REGULATIONS 		</li>
    <li onclick="regiv()">		ARENA			</li>  
</ul>

<div id="div_intro">
<br />
<h3>INTRODUCTION:</h3>
        From the moment "GO" begins the race and all throughout you keep dreaming of just one place, The Check line. Gripping the ground and raising the gear you keep moving but finally comes the fear and apart from winning you just don't care. When your IC engine car hits the race let the track itself say, oh!! Here comes the one that shall show you the way.
    <h4>EVENT COORDINATOR:</h4>
    <ul>    <li>	Mr. Sanjay Sharma					9977197447</li>    </ul>
    
    <h4>EVENT MANAGERS: </h4>
	<ul><li>Jaspreet Singh			9993796609</li>
	<li>Md. Ahtesham Rana		9300521422	</li></ul>
    <b>REGISTRATION FEES: </b>500/- PER TEAM
</div>

<div id="div_prblm" style="display:none">
<br />
<H3>PROBLEM STATEMENT</H3>

Make a wireless remote controlled machine, powered by only an IC engine, which can race against other opponents on an off-road dirt track with many obstacles. 

<H4>Machine Specifications</H4>
<ol>
<li>	Machine should fit in a box of dimensions 800 mm x 600 mm x 600 mm (l x b x h) at any moment of time during the race. The external device which is used to control the machine is not included in the size constraint.</li>
<li>	The machine should be controlled by a wireless remote control mechanism throughout the race.</li>
<li>	The machine must not be made from Lego parts, or any ready-made assembly kits other than the parts mentioned below. Readily available chassis layouts are not allowed. Any machine found having a ready-made chassis will be disqualified.</li>
<li>	The machine may be roughly classified into structural and functional parts:</li>
<li>Functional parts - Gears, differential gear, engine, springs, shock absorbers, servo motors (non-propulsion purposes only), batteries, wheels, wheel hub are allowed to be used as available in the market.</li>
<li>	Structural parts - Chassis, steering mechanism, shock towers and suspension (excluding upper suspension arm, suspension spring and shock absorbers) have to be built by the participants themselves.</li>
<li>	Judging for the same will be strict and the participant will be immediately disqualified if any of the above structural components are found to be ready-made.</li>
<li>	The tires used must have a minimum diameter of 3 inches. You are advised to use tyres of good width for better performance on dirt tracks. <br />
<img src="sho/FT/ft1.jpg" title="Figure 1" /> </li>

<li>	Brake Mechanism: It is compulsory to incorporate braking mechanism in the car. Participants have to fabricate the brake pad as a part of the braking mechanism. Any other part used in braking mechanism (including the brake disk) can be ready-made. <br />
<img src="sho/FT/ft2.jpg" />
<img src="sho/FT/ft3.jpg" />
</li>
 	 
<li>	Wheel Hub: Any part rigidly attached to the wheel hub will be considered as a part of it and hence can be ready-made. An example here is that of the ball stud.<br />
<img src="sho/FT/ft4.jpg" />
</li>

<li>	Steering Mechanism: Any part which is connected to steering rod rigidly i.e. has no degrees of freedom with respect to steering rod (example: heim joint) will be considered as part of steering rod and thus has to be fabricated by participants.<br />
<img src="sho/FT/ft5.jpg" />
<img src="sho/FT/ft6.jpg" />
</li>

<li>	Suspension mechanism: Any part rigidly connected to suspension arms or one with no degrees of freedom with respect to suspension arm will be considered as its part and has to be fabricated by the participants, except the upper suspension arm. For example both the heim joint for the upper suspension arm and the stud rigidly connected to the wheel hub can be bought from the market.<br />
<img src="sho/FT/ft7.jpg" />
<img src="sho/FT/ft8.jpg" />

<br />
If there are parts used in the concerned joint which are neither rigidly connected with suspension or the hub, steering system or hub; they can be used ready-made from the market.
</li>

<li>	The above pictures are just sample pictures for you to understand the rules easily.</li>
</ol>

<h4 >Propulsion & Steering</h4>
<ol>
<li>	The machine must use only mechanical power generated by an internal combustion (IC) engine for propulsion. Only one IC engine should be used in the machine. Use of any other sources such as chemicals, compressed gas, rockets etc. is not allowed.</li>
<li>	Any machine which uses DC Motors for propulsion will be disqualified. However DC motors and servos can be used for steering mechanisms or any other control mechanisms apart from propulsion.</li>
<li>	The machine must have an on-board power supply to run any mechanism requiring electric power.</li>
<li>	The maximum allowed capacity of IC engine to be used is 4.6 cc (i.e. Participants can also use 2.5 cc, 3 cc, 3.5 cc or any other IC engine lower in capacity).</li>
<li>	The electric voltage anywhere in the machine should not exceed 12V at any point of time.</li>
<li>	There shall be a countdown preceding the start of the race. No participant is allowed to touch the machine during the countdown period.</li>
<li>	Providing a clutch mechanism between the engine and the wheel would prove useful, as it would prevent the engine from dying out at any stage of the race.</li>
<li>	Participants are advised to use a proper cooling mechanism to prevent overheating of the engine</li>
<li>	Participants are advised to use sway bars for better control and stability.</li>
<li>	The participants are advised to use proper air filters as dirt might cause serious problems to the engine.</li>
<li>	Readymade wheels are allowed.</li>
<li>	The machine will be inspected and if found to be dangerous, the team will be disqualified. This decision rests solely with the judges and the organizers.</li>
</ol>

</div>


<div id="div_rules" style="display:none">
<br />
<h4>RULES AND REGULATIONS:</h4>
<ol>
<li>	There will be a qualifying session with each team getting 2 laps out of which the faster lap will be considered. Note that these laps will have to be taken successively.</li>
<li>	The top teams from the qualifying rounds will make it to the second round.</li>
<li>	After the qualifying round there will be races with multiple cars racing at a time. So the participants must use remote with frequency of band spectrum 2.4 GHz.</li>
<li>	The track will have check points at regular intervals. If a machine tumbles, or halts, or goes off the arena at any point on the track, one of the team members is allowed to lift it up and place it at the nearest checkpoint behind that point. The time shall still be running in the meantime.</li>
<li>	Team members are not permitted to touch either their machines or those of their opponents once the race begins (unless there is need to lift the machine as stated in fourth point). The penalty for doing so is disqualification.</li>
<li>	In the qualification round there will be maximum two team members allowed from a team in the racing arena while in the final round only one of the team member will be in the racing arena except the controller on the stand.</li>
<li>	The machines are not allowed to leave any loose parts on any part of the arena. Any machine disintegrating during the race will be disqualified.</li>
<li>	If any of the machines starts off before the flag is waved, the counter would be restarted and the machines will get a second chance. However, if any machine starts off before the waving of flag (or countdown) for a second time, it will be disqualified. No re-match will be held for the second time.</li>
<li>	Teams are not allowed to purposefully damage the machine of the opponent's team. If found doing so on track (while racing), the concerned team will be disqualified. Execution of last three rules will be subjective and relies completely on judges' discretion.</li>
</ol>

<h4>CONTROL RULES:</h4>
<ol>
<li>	Participants are required to use a remote control of frequency of band spectrum 2.4 GHz.</li>
<li>	The above rule is to ensure that there is no frequency clash during the competition and participants are not allowed to use any other remotes with frequency other than 2.4 GHz.</li>
</ol>

<h4>GENERAL RULES:</h4>
<ol>
<li>	The teams may obtain a time slot for practice before first round of the game. The number of practice slots will be limited and the slots will be given on a first come first served basis. The teams will get to use the track only during the time of their practice slot. Any requests for using the track at any other time will not be entertained.</li>
<li>	Any team that is not ready at the time specified will be eliminated from the competition automatically.</li>
<li>	The teams must adhere to the spirit of healthy competition. The teams must not damage the opponent's machine in any way. Judges reserve the right to disqualify any team indulged in misbehaviour.</li>
<li>	The name of your machine should be prominently displayed on the machine.</li>
<li>	Judges decision shall be treated as final and binding on all.</li>
<li>	The organizers reserve the rights to change any or all of the above rules as they deem fit. Change in rules, if any will be highlighted on the website and notified to the registered participants.</li>
</ol>

<h4>JUDGING CRITERION:</h4>
In the qualification round on the basis of individual best times for completing one lap, top teams will be selected who will get into the final round. In the finals multiple teams will race together to triumph over the others.
<h4>TEAM SPECIFICATIONS:</h4>
A team may consist of a maximum of 5 participants. Students from different educational institutes can form a team.

</div>

<div id="div_regi" style="display:none">
<br />
<h4>ARENA </h4>
The track will be an all terrain track with sharp turns and big jumps. In this edition of Full Throttle both speed and control will be important. The car should be able to cross bumps, jumps and other obstacles on the track and outdo the opponents' car while maintaining its stability and not compromising on its pace. The track will be an off road track. Most parts of the track will be made up of mud, however at a few places wood and jute mat can be used.
The obstacles in the track are as follows:
<ol>
<li>	One Big bump of 1.5 feet height and width 3 feet.</li>
<li>	Small bumps of 3 inch diameter and of semi-circular shape.</li>
<li>	Small Jump of height 6 inch and length 2.5 feet</li>
<li>	Big Jump of height 1 feet and length 4 feet.</li>
<li>	Bumps in the form of inverted baskets of diameter 16 inch and maximum height of 3 inch.</li>
<li>	Trees of width 1-2 feet may be present obstructing the vision of driver.</li>
<li>	The width of the track will be around 7 feet for most of the part.</li>
<li>	A control stand will be provided along the track for the driver to position himself to control his vehicle during the run. The height of the stand will be around 8 feet. The controlling of machine has to be done from this site only.</li>
<li>	Despite organizers efforts to keep the track quality intact, the track is subjected to undergo wear and tear as machines run over it. The machine is expected to be able to perform on such a weakened track.</li>
<li>	Multiple machines will race on a single lane track at a time.</li>
<li>	A lap of the track is defined to be completed when the machine comes back to the start-finish line.</li>
</ol>

<img src="sho/FT/basket-1.jpg" />
<img src="sho/FT/big_bump.jpg" />
<img src="sho/FT/big_ramp.jpg" />
<img src="sho/FT/small_bump.jpg" /> 

</div>